SCREEN_WIDTH = 960
SCREEN_HEIGHT = 540
FULLSCREEN = False
SHOW_FPS = False
SHOW_HITBOX = False
SHOW_GRID = False
SHOW_LINE_OF_SIGHT = False
TILE_SIZE = 32
ROWS = 25
COLS = 25
DISPLAY_WIDTH = 480
DISPLAY_HEIGHT = 270
SCROLL_THRESH_X = 200
SCROLL_THRESH_Y = 100
SCALE_WIDTH = SCREEN_WIDTH/DISPLAY_WIDTH
SCALE_HEIGHT = SCREEN_HEIGHT/DISPLAY_HEIGHT
SPEED = 2
ARROW_SPEED = 10
RED = (255,0,0)
WHITE = (255,255,255)
BLACK = (0,0,0)
DARKRED = (153, 0, 0)
COLORHUD = (31, 0, 0)
BROWN = (79, 53, 8)
MAINMENU_COLOR = (71, 34, 18)
MAINMENU_COLOR_DARKER = (66, 28, 10)
GREEN = (20, 204, 69)
BLUE = (0,0,255)
GREY = (76, 76, 77)
YELLOW = (197, 217, 20)
BG = (38, 48, 17)
PLAYER_HP = 100
GOLD = 1000
ORC_HP = 50
ORC_SPEED = 1
ORC_RANGE = 150
ORC_SHAMAN_HP = 300
MAGIC_BALL_SPEED = 4
MUSIC = True
MUSIC_VOLUME = 0.3
FX_VOLUME = 0.5
FADE_SPEED = 7
AMOUNT_OF_HEROS = 0
SLIME_SPEED = 1
SLIME_HP = 50
HERO = ''
SLIME_RANGE = 100
TROLL_RANGE = 150
WOLF_RANGE = 200
TROLL_AIM_RANGE = 100
TROLL_DAMAGE = 20
GOBLIN_RANGE = 120
ENT_RANGE = 200 
ENT_DAMAGE = 30
SLIME_FIRE_WIZARD_RANGE = 100
WOLF_HP = 30
TROLL_HP = 65
GOBLIN_HP = 75
ENT_HP = 30
SLIME_FIRE_WIZARD_HP = 300
DRUID_HP = 1000
TYPES_OF_WEAPONS =['bows', 'throwables', 'two_handed_swords', 'spears']
BOWS = ['slingshot' , 'classic_bow', 'composite_bow', 'crossbow', 'deer_tamer', 'iron_bow', 'lava_guardian_crossbow']
THROWABLES = ['rock', 'knive', 'throwing_axe', 'throwing_spear', 'broken_druid_staff', 'crusader_throwing_axe', 'lava_defenders_penetrator']
TWOHANDEDSWORDS = ['wooden_sword', 'rusted_sword', 'sword', 'katana', 'great_sword', 'sharpened_druid_staff', 'master_curved_slasher']
SPEARS = ['wooden_spear', 'spear', 'extended_sickle', 'guard_spear', 'wooden_pitchfork', 'pitchfork' , 'blade_on_stick', "pike_with_a_wolf's_tooth", "angel's_spear"]
DRUID_DEFEAT = False
CARDS = ['health_card', 'light_attack_card', 'heavy_attack_card']